import 'package:flutter/material.dart';
import 'package:get/get.dart';

enum EquipmentType {
  allEquipments,
  noEquipment,
  barbell,
  dumbbell,
  kettlebell,
  machine,
  plate,
  resistanceBand,
  suspensionBand,
  other,
}

enum Muscle {
  allMuscles,
  abdominals,
  abductors,
  adductors,
  lowerBack,
  upperBack,
  biceps,
  cardio,
  chest,
  calves,
  forearms,
  glutes,
  hamstrings,
  lats,
  shoulders,
  traps,
  triceps,
  quadriceps,
  olympic,
  fullBody,
  other,
}

enum Difficulty {
  basic,
  intermediate,
  advance,
}

class ExerciseStepModel {
  final String name;
  final String image;
  final bool needEquipment;
  final EquipmentType equipmentType;
  final Muscle muscle;
  final Difficulty difficulty;

   ExerciseStepModel(
    this.name,
    this.image,
    this.needEquipment,
    this.equipmentType,
    this.muscle,
    this.difficulty,
  );
}


List exercise =  [
  ExerciseStepModel(
    'Archer-Push-Up',
    'assets/images/Archer-Push-Up.gif',
    false,
    EquipmentType.noEquipment,
    Muscle.fullBody,
    Difficulty.intermediate,
  ),
  ExerciseStepModel(
    'Barbell-Bent-Over-Row',
    'assets/images/Barbell-Bent-Over-Row.gif',
    true,
    EquipmentType.barbell,
    Muscle.fullBody,
    Difficulty.advance,
  ),
  ExerciseStepModel(
    'Barbell-Clean-and-Press',
    'assets/images/Barbell-Clean-and-Press.gif',
    true,
    EquipmentType.barbell,
    Muscle.fullBody,
    Difficulty.advance,
  ),
  ExerciseStepModel(
    'Barbell-Hang-Clean',
    'assets/images/Barbell-Hang-Clean.gif',
    true,
    EquipmentType.barbell,
    Muscle.fullBody,
    Difficulty.advance,
  ),
  ExerciseStepModel(
    'Barbell-Heaving-Snatch-Balance',
    'assets/images/Barbell-Heaving-Snatch-Balance.gif',
    true,
    EquipmentType.barbell,
    Muscle.fullBody,
    Difficulty.advance,
  ),
  ExerciseStepModel(
    'Barbell-Muscle-Snatch',
    'assets/images/Barbell-Muscle-Snatch.gif',
    true,
    EquipmentType.barbell,
    Muscle.fullBody,
    Difficulty.intermediate,
  ),
  ExerciseStepModel(
    'Barbell-Power-Snatch',
    'assets/images/Barbell-Power-Snatch.gif',
    true,
    EquipmentType.barbell,
    Muscle.fullBody,
    Difficulty.basic,
  ),
  ExerciseStepModel(
    'Barbell-Snatch',
    'assets/images/Barbell-Snatch.gif',
    true,
    EquipmentType.barbell,
    Muscle.fullBody,
    Difficulty.basic,
  ),
  ExerciseStepModel(
    'Battle-Rope',
    'assets/images/Battle-Rope.gif',
    true,
    EquipmentType.other,
    Muscle.fullBody,
    Difficulty.advance,
  ),
  ExerciseStepModel(
    'Bent-Over-Dumbbell-Row',
    'assets/images/Bent-Over-Dumbbell-Row.gif',
    true,
    EquipmentType.dumbbell,
    Muscle.fullBody,
    Difficulty.intermediate,
  ),
  ExerciseStepModel(
    'Bodyweight-Skull-Crushers',
    'assets/images/Bodyweight-Skull-Crushers.gif',
    false,
    EquipmentType.noEquipment,
    Muscle.fullBody,
    Difficulty.intermediate,
  ),
  ExerciseStepModel(
    'burpees',
    'assets/images/burpees.gif',
    false,
    EquipmentType.noEquipment,
    Muscle.fullBody,
    Difficulty.basic,
  ),
  ExerciseStepModel(
    'Cross-Body-Push-up_Plyometric',
    'assets/images/Cross-Body-Push-up_Plyometric.gif',
    false,
    EquipmentType.noEquipment,
    Muscle.fullBody,
    Difficulty.basic,
  ),
  ExerciseStepModel(
    'Dumbbell-Burpees',
    'assets/images/Dumbbell-Burpees.gif',
    true,
    EquipmentType.dumbbell,
    Muscle.fullBody,
    Difficulty.advance,
  ),
  ExerciseStepModel(
    'Dumbbell-Devil-Press',
    'assets/images/Dumbbell-Devil-Press.gif',
    true,
    EquipmentType.dumbbell,
    Muscle.fullBody,
    Difficulty.intermediate,
  ),
  ExerciseStepModel(
    'Dumbbell-Iron-Cross',
    'assets/images/Dumbbell-Iron-Cross.gif',
    true,
    EquipmentType.dumbbell,
    Muscle.fullBody,
    Difficulty.advance,
  ),
  ExerciseStepModel(
    'Dumbbell-Jump-Squat',
    'assets/images/Dumbbell-Jump-Squat.gif',
    true,
    EquipmentType.dumbbell,
    Muscle.fullBody,
    Difficulty.advance,
  ),
  ExerciseStepModel(
    'Dumbbell-Power-Clean',
    'assets/images/Dumbbell-Power-Clean.gif',
    true,
    EquipmentType.dumbbell,
    Muscle.fullBody,
    Difficulty.advance,
  ),
  ExerciseStepModel(
    'Farmers-walk_Cardio',
    'assets/images/Farmers-walk_Cardio.gif',
    true,
    EquipmentType.dumbbell,
    Muscle.fullBody,
    Difficulty.basic,
  ),
  ExerciseStepModel(
    'Human-Flag',
    'assets/images/Human-Flag.gif',
    true,
    EquipmentType.other,
    Muscle.fullBody,
    Difficulty.advance,
  ),
  ExerciseStepModel(
    'Impossible-Dips',
    'assets/images/Impossible-Dips.gif',
    true,
    EquipmentType.other,
    Muscle.fullBody,
    Difficulty.advance,
  ),
];
